### PR TITLE
Added a channel check & conversion inside countCircles.

### PR DESCRIPTION
**Pull request by RobynCastro**
- Uses a switch case statement to check for channel number.
  - Based on channel number found, converts that image to a grayscale image.
  - Possibly not all channel cases have been accounted for (Added TODO)

### CODE REVIEW

**Comment by garethellis0** [comment]
Ideally we don't start merging PR's with TODO's in them. Could we maybe just change the TODO to a comment indicating that 4 and 3 should cover most cases, but if there are issues in the future, this would be a good place to start looking?

**Comment by garethellis0** [comment]
**Note to self:** @RobynCastro has indicated this might have some issues still and wants to test it some more before merging

**Comment by garethellis0** [comment]
@RobynCastro - is this good to be merged?

**Comment by RobynCastro** [comment]
Yeah it should be good!

**Comment by garethellis0** [comment]
Great, thanks @RobynCastro

**Pull request merged**
